FROM golang:1.26-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY services/auth-service/go.mod services/auth-service/go.sum* ./

RUN go mod download

COPY services/auth-service/ .

EXPOSE 50051

CMD ["air"]
